import type { Metadata } from 'next'
import { Oswald } from 'next/font/google'
import './globals.css'
import Navbar from './navbar/Navbar'
import Footer from './Footer/Footer'

const oswald = Oswald({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AIT STUDIOS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en " className='!scroll-smooth   bg-orange-300 '>
      <body className={'${inter.className} sm:max-w-screen-xl'}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
